# hello-go-deploy-marathon task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
- name: hello-go-deploy-marathon

outputs:
- name: hello-go-deploy-marathon-updated

run:
  path: ./hello-go-deploy-marathon/ci/scripts/readme-github-pages.sh
  # args: [-debug]
