# hello-go-deploy-marathon task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.3

inputs:
- name: resource-github-repo

outputs:
- name: resource-github-repo-updated

run:
  path: ./hello-go-deploy-marathon/ci/scripts/readme-github-pages.sh
  # args: [-debug]
