# hello-go-deploy-marathon task-build.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-marathon

outputs:
- name: dist

run:
  path: ./hello-go-deploy-marathon/ci/scripts/build.sh
