# hello-go-deploy-marathon task-build-push.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-marathon

outputs:
- name: dist

run:
  path: ./hello-go-deploy-marathon/ci/scripts/build-push.sh
  # args: [-concourse]
  args: [-concourse -debug]
