# hello-go-deploy-marathon task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-marathon

run:
  path: ./hello-go-deploy-marathon/ci/scripts/deploy.sh